spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://47.107.104.181:12345/microservice?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://47.107.104.181:8082/eureka
env:
  dev
